### ISSUE TITLE
spin-core imports JUnit packages in its MANIFEST

### ISSUE THREAD

**Issue by rbraeunlich** [camunda/camunda-spin#6]
It shouldn't do that

**Comment by menski** [comment]
Hi Ronny,

sorry for the late response. :worried: 

I assume this is caused by the fact the spin core contains the ScriptRule.java, ScriptEngineRule.java and ScriptTest.java. Which use/extend JUnit classes.

Should JUnit than still be removed from the manifest? Do you know how to do this? :confused: 

Cheers,
Sebastian

**Comment by ThorbenLindhauer** [comment]
Should probably become optional like in `camunda-engine`.

**Comment by menski** [comment]
@ThorbenLindhauer you like this: https://github.com/camunda/camunda-bpm-platform/blob/0fedcf3173e235ca17815986e0abfb3ba6d5795b/engine/pom.xml#L233-L234

**Comment by ThorbenLindhauer** [comment]
Yes. Would like to hear Ronny's thoughts on this, though, since he is the OSGi expert.

**Comment by rbraeunlich** [comment]
Hey,
that's really a late response ^^
I agree with Thorben, that we should make it optional, since we've used this approach already for the engine.
Cheers,
Ronny
